Repository Robert076/UBB-SE-2025-GitPushForce, pull requests merged in 2025-03, with the labels that each got.

#70 Feat/bolos/model bill split
  Model/BillSplitReport.cs
  Model/README.md
Labels: Task

#77 removed unnecesary files. now code runs
  src.csproj
Labels: fix

#75 activity log model
  Model/ActivityLog.cs
Labels: Task

#91 chat report feature done
  App.xaml
  Data/Scripts/mock.sql
  Data/Scripts/procedures.sql
  MainWindow.xaml
  MainWindow.xaml.cs
  Model/ChatReport.cs
  Repos/ChatReportRepository.cs
  Repos/UserRepository.cs
  Services/ChatReportService.cs
  View/Components/ChatReportComponent.xaml
  View/Components/ChatReportComponent.xaml.cs
  View/Pages/ChatReportView.xaml
  View/Pages/ChatReportView.xaml.cs
  View/Pages/LoanRequestView.xaml
  View/Pages/LoanRequestView.xaml.cs
  View/README.md
  ViewModel/ChatReportViewModel.cs
  src.csproj
Labels: enhancement

#79 Feat/balau/data collection stocks
  Model/Investment.cs
Labels: Task
